bases:
- ../../../base/admindeployment

namespace: flyte

resources:
- cron.yaml

configMapGenerator:
# the main admin configmap
- name: flyte-admin-config
  files:
    - flyteadmin_config.yaml
# cluster resource templates
- name: clusterresource-template
  files:
# Files are read in alphabetical order. To ensure that we create the namespace first, prefix the file name with "aa".
    - clusterresource-templates/aa_namespace.yaml
    - clusterresource-templates/ab_project-resource-quota.yaml
    - clusterresource-templates/ac_project-copilot-dataconfig.yaml
    - clusterresource-templates/ad_spark-role.yaml
    - clusterresource-templates/ae_spark-service-account.yaml
    - clusterresource-templates/af_spark-role-binding.yaml
patches:
- admindeployment.yaml
