# For docker-desktop at least, the range of valid ports is 30000-32767, which is why we're constrained to these
# odd port numbers. Since the base ingress runs on 30081, the K8s dashboard runs on 30082, these just continue from there.
# These nodeports are exposed to save contributors the trouble of port forwarding when running locally.

apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres-direct
  namespace: flyte
spec:
  ports:
  - nodePort: 30083
    port: 5432
    protocol: TCP
  selector:
    app: postgres
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
  name: minio-direct
  namespace: flyte
spec:
  ports:
  - nodePort: 30084
    port: 9000
    protocol: TCP
  selector:
    app: minio
  type: NodePort
