apiVersion: apps/v1
kind: Deployment
metadata:
  name: datacatalog 
  namespace: flyte
spec:
  template:
    spec:
      containers:
      - name: datacatalog 
        resources:
          limits:
            memory: "200Mi"
            cpu: "0.1"
            ephemeral-storage: "100Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: datacatalog 
  namespace: flyte
