name: tests
on:
  push:
    branches:
    - master
  pull_request:
jobs:
  end-to-end:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Kustomize and diff
      run: DELTA_CHECK=true make kustomize
    - uses: engineerd/setup-kind@v0.4.0
    - name: End2End
      env:
        DOCKER_USERNAME: ${{ github.actor }}
        DOCKER_PASSWORD: "${{ secrets.GITHUB_TOKEN }}"
      run: |
        kubectl cluster-info
        kubectl get pods -n kube-system
        echo "current-context:" $(kubectl config current-context)
        echo "environment-kubeconfig:" ${KUBECONFIG}
        make end2end_execute
  docs:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    steps:
    - uses: actions/checkout@v1
    - name: Build docs
      run: make generate-docs
